### ISSUE TITLE
Genesis.Ensure 1.0.5-alpha is missing .. cannot build

### ISSUE THREAD

**Issue by dhaligas** [kentcb/WorkoutWotch#6]
Genesis.Ensure 1.0.5-alpha is missing 

Nuget cannot restore this package.

**Comment by kentcb** [comment]
@dhaligas thanks for reporting this. I accidentally left in a dependency on a local package. I've fixed this now.

**Comment by dhaligas** [comment]
@kentcb also the optimize images I had to roll back to get it to build .. the pngs were invalid

**Comment by kentcb** [comment]
@dhaligas hmmm, that's weird. I'm able to build for both platforms OK with VS on Windows. Are you perhaps using XS?

**Comment by dhaligas** [comment]
yes on a mac using Xam Studio

**Comment by kentcb** [comment]
Thanks, I think it was actually the git settings that were strangely causing it to convert line feed characters in binary files. I've updated the config and reverted the files just in case.
